export interface NutritionFacts {
  servingSize: number; // 30
  calories: number; // 120
  sodium?: number; // 150 (mg)
  carbs: number; // 10 (g)
  sugar: number; // 2 (g)
  protein: number; // 20 (g)
  fat?: number; // 1.5 (g)
  saturatedFat?: number; // 0.5 (g)
  transFat?: number; // 0 (g)
  cholesterol?: number; // 5 (mg)
  calcium?: number; // 100 (mg)
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  image: string;
  images?: string[]; // 추가 이미지들
  favorites: number;
  flavor: string;
  proteinType: string;
  purchaseUrl?: string; // 구매 링크
  nutritionFacts: NutritionFacts; // 영양성분
  totalAmount?: number; // 총 내용량 (예: 630)
  servingsPerContainer?: number; // 총 회분 (예: 12)
}

export const products: Product[] = [
  {
    id: "1",
    name: "프리미엄 웨이 초코맛 대용량",
    brand: "머슬팜",
    image: "/api/placeholder/400/400",
    images: [
      "/api/placeholder/400/400",
      "/api/placeholder/400/401",
      "/api/placeholder/400/402",
      "/api/placeholder/400/403",
    ],
    favorites: 1248,
    flavor: "초코",
    proteinType: "분리유청단백(WPI)",
    purchaseUrl: "https://example.com/products/1",
    totalAmount: 630,
    servingsPerContainer: 21,
    nutritionFacts: {
      servingSize: 30,
      calories: 120,
      sodium: 150,
      carbs: 3,
      sugar: 1,
      protein: 25,
      fat: 1.5,
      saturatedFat: 0.5,
      transFat: 0,
      cholesterol: 5,
      calcium: 100,
    },
  },
  {
    id: "2",
    name: "골드 스탠다드 딸기맛",
    brand: "옵티멈 뉴트리션",
    image: "/api/placeholder/400/410",
    images: ["/api/placeholder/400/410", "/api/placeholder/400/411", "/api/placeholder/400/412"],
    favorites: 892,
    flavor: "딸기",
    proteinType: "농축유청단백(WPC)",
    purchaseUrl: "https://example.com/products/2",
    totalAmount: 908,
    servingsPerContainer: 30,
    nutritionFacts: {
      servingSize: 30,
      calories: 110,
      carbs: 4,
      sugar: 2,
      protein: 24,
      fat: 1.0,
    },
  },
  {
    id: "3",
    name: "식물성 프로틴 바나나맛",
    brand: "가든 오브 라이프",
    image: "/api/placeholder/400/420",
    images: ["/api/placeholder/400/420", "/api/placeholder/400/421"],
    favorites: 567,
    flavor: "바나나",
    proteinType: "완두단백",
    purchaseUrl: "https://example.com/products/3",
    totalAmount: 450,
    servingsPerContainer: 15,
    nutritionFacts: {
      servingSize: 30,
      calories: 100,
      carbs: 7,
      sugar: 3,
      protein: 20,
      fat: 2.0,
    },
  },
  {
    id: "4",
    name: "카제인 프로틴 말차맛",
    brand: "다이마타이즈",
    image: "/api/placeholder/300/300",
    favorites: 423,
    flavor: "말차",
    proteinType: "카제인",
    purchaseUrl: "https://example.com/products/4",
    nutritionFacts: {
      servingSize: 30,
      calories: 130,
      carbs: 5,
      sugar: 2,
      protein: 25,
      fat: 1.5,
    },
  },
  {
    id: "5",
    name: "현미 프로틴 곡물맛",
    brand: "선플라워",
    image: "/api/placeholder/300/300",
    favorites: 234,
    flavor: "곡물",
    proteinType: "현미단백",
    purchaseUrl: "https://example.com/products/5",
    nutritionFacts: {
      servingSize: 30,
      calories: 115,
      carbs: 8,
      sugar: 4,
      protein: 22,
      fat: 2.5,
    },
  },
  {
    id: "6",
    name: "아이솔레이트 밀크티맛",
    brand: "BSN",
    image: "/api/placeholder/300/300",
    favorites: 678,
    flavor: "밀크티",
    proteinType: "분리유청단백(WPI)",
    purchaseUrl: "https://example.com/products/6",
    nutritionFacts: {
      servingSize: 30,
      calories: 125,
      carbs: 2,
      sugar: 1,
      protein: 26,
      fat: 1.0,
    },
  },
  {
    id: "7",
    name: "오가닉 웨이 녹차맛",
    brand: "오가니카",
    image: "/api/placeholder/300/300",
    favorites: 345,
    flavor: "녹차",
    proteinType: "농축유청단백(WPC)",
    purchaseUrl: "https://example.com/products/7",
    nutritionFacts: {
      servingSize: 30,
      calories: 105,
      carbs: 6,
      sugar: 3,
      protein: 21,
      fat: 1.5,
    },
  },
  {
    id: "8",
    name: "하이드로 웨이 커피맛",
    brand: "프로탄",
    image: "/api/placeholder/300/300",
    favorites: 789,
    flavor: "커피",
    proteinType: "가수분해유청단백(WPH)",
    purchaseUrl: "https://example.com/products/8",
    nutritionFacts: {
      servingSize: 30,
      calories: 135,
      carbs: 3,
      sugar: 1,
      protein: 27,
      fat: 1.2,
    },
  },
  {
    id: "9",
    name: "초유 프로틴 플레인",
    brand: "콜로스트럼킹",
    image: "/api/placeholder/300/300",
    favorites: 156,
    flavor: "기타",
    proteinType: "초유",
    purchaseUrl: "https://example.com/products/9",
    nutritionFacts: {
      servingSize: 30,
      calories: 120,
      carbs: 4,
      sugar: 2,
      protein: 23,
      fat: 1.8,
    },
  },
  {
    id: "10",
    name: "귀리 프로틴 시나몬맛",
    brand: "오트프로",
    image: "/api/placeholder/300/300",
    favorites: 445,
    flavor: "기타",
    proteinType: "귀리단백",
    purchaseUrl: "https://example.com/products/10",
    nutritionFacts: {
      servingSize: 30,
      calories: 140,
      carbs: 12,
      sugar: 6,
      protein: 19,
      fat: 3.0,
    },
  },
  {
    id: "11",
    name: "난백 프로틴 바닐라맛",
    brand: "에그프로",
    image: "/api/placeholder/300/300",
    favorites: 267,
    flavor: "기타",
    proteinType: "난백",
    purchaseUrl: "https://example.com/products/11",
    nutritionFacts: {
      servingSize: 30,
      calories: 110,
      carbs: 1,
      sugar: 0,
      protein: 24,
      fat: 0.5,
    },
  },
  {
    id: "12",
    name: "산양유 프로틴 초코맛",
    brand: "고트프로틴",
    image: "/api/placeholder/400/480",
    favorites: 123,
    flavor: "초코",
    proteinType: "산양유",
    purchaseUrl: "https://example.com/products/12",
    nutritionFacts: {
      servingSize: 30,
      calories: 115,
      carbs: 5,
      sugar: 3,
      protein: 22,
      fat: 2.0,
    },
  },
  // 머슬팜 추가 제품들 (연관상품용)
  {
    id: "13",
    name: "프리미엄 웨이 바닐라맛",
    brand: "머슬팜",
    image: "/api/placeholder/400/500",
    images: ["/api/placeholder/400/500", "/api/placeholder/400/501", "/api/placeholder/400/502"],
    favorites: 956,
    flavor: "바닐라",
    proteinType: "분리유청단백(WPI)",
    purchaseUrl: "https://example.com/products/13",
    nutritionFacts: {
      servingSize: 30,
      calories: 118,
      carbs: 3,
      sugar: 1,
      protein: 25,
      fat: 1.5,
    },
  },
  {
    id: "14",
    name: "프리미엄 웨이 딸기맛",
    brand: "머슬팜",
    image: "/api/placeholder/400/510",
    favorites: 734,
    flavor: "딸기",
    proteinType: "분리유청단백(WPI)",
    purchaseUrl: "https://example.com/products/14",
    nutritionFacts: {
      servingSize: 30,
      calories: 122,
      carbs: 4,
      sugar: 2,
      protein: 25,
      fat: 1.6,
    },
  },
  {
    id: "15",
    name: "프리미엄 웨이 쿠키크림맛",
    brand: "머슬팜",
    image: "/api/placeholder/400/520",
    favorites: 623,
    flavor: "쿠키크림",
    proteinType: "분리유청단백(WPI)",
    purchaseUrl: "https://example.com/products/15",
    nutritionFacts: {
      servingSize: 30,
      calories: 125,
      carbs: 4,
      sugar: 2,
      protein: 24,
      fat: 1.8,
    },
  },
  // 옵티멈 뉴트리션 추가 제품들
  {
    id: "16",
    name: "골드 스탠다드 초코맛",
    brand: "옵티멈 뉴트리션",
    image: "/api/placeholder/400/530",
    images: ["/api/placeholder/400/530", "/api/placeholder/400/531"],
    favorites: 1156,
    flavor: "초코",
    proteinType: "농축유청단백(WPC)",
    purchaseUrl: "https://example.com/products/16",
    nutritionFacts: {
      servingSize: 30,
      calories: 113,
      carbs: 3,
      sugar: 1,
      protein: 24,
      fat: 1.0,
    },
  },
  {
    id: "17",
    name: "골드 스탠다드 바나나맛",
    brand: "옵티멈 뉴트리션",
    image: "/api/placeholder/400/540",
    favorites: 445,
    flavor: "바나나",
    proteinType: "농축유청단백(WPC)",
    purchaseUrl: "https://example.com/products/17",
    nutritionFacts: {
      servingSize: 30,
      calories: 112,
      carbs: 4,
      sugar: 2,
      protein: 24,
      fat: 1.2,
    },
  },
  {
    id: "18",
    name: "골드 스탠다드 바닐라맛",
    brand: "옵티멈 뉴트리션",
    image: "/api/placeholder/400/550",
    favorites: 789,
    flavor: "바닐라",
    proteinType: "농축유청단백(WPC)",
    purchaseUrl: "https://example.com/products/18",
    nutritionFacts: {
      servingSize: 30,
      calories: 108,
      carbs: 3,
      sugar: 1,
      protein: 24,
      fat: 1.0,
    },
  },
];

// 필터 옵션들
export const flavorOptions = [
  "전체",
  "초코",
  "딸기",
  "바나나",
  "말차",
  "곡물",
  "밀크티",
  "녹차",
  "커피",
  "기타",
];

export const proteinTypeOptions = [
  "전체",
  "산양유",
  "초유",
  "농축유청단백(WPC)",
  "분리유청단백(WPI)",
  "가수분해유청단백(WPH)",
  "가수분해분리유청단백(WPIH)",
  "분리대두단백(ISP)",
  "농축대두단백(SPC)",
  "완두단백",
  "현미단백",
  "귀리단백",
  "농축우유단백(MPC)",
  "분리우유단백(MPI)",
  "카제인",
  "난백",
];
